### ISSUE TITLE
marisa cross-over contents does not show up

### ISSUE THREAD

**Issue by crownbird** [scarf005/Marisa#226] opened 2023-12-02 01:45 UTC
### How to reproduce

Tested cross-content mods

gensokyo act mod (marisa-exclussive dialogue and event does not show up)

### Game language

English (ENG)

**Comment by scarf005** [comment] 2023-12-06 02:21
thanks for the report. however, i'm afraid that this issue duplicate of #147.

**Closed as not planned by scarf005** 2023-12-06 02:21 UTC
Labels: bug
